/**
 * Schema.org JSON-LD Generator for TextToSpeechH AI
 * Brand Name: TextToSpeechH AI
 * Website: https://www.texttospeechh.com
 * Official Social: Instagram @webxpert.ai (https://www.instagram.com/webxpert.ai/)
 * Primary Contact: hello@texttospeechh.com
 * Customer Support: support@texttospeechh.com
 */

const DOMAIN = "https://www.texttospeechh.com";
const BRAND_NAME = "TextToSpeechH AI";
const CONTACT_EMAIL = "hello@texttospeechh.com";
const SUPPORT_EMAIL = "support@texttospeechh.com";
const OFFICIAL_INSTAGRAM = "https://www.instagram.com/webxpert.ai/";

function getOrganizationSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    "name": BRAND_NAME,
    "url": DOMAIN,
    "logo": `${DOMAIN}/logo.svg`,
    "email": CONTACT_EMAIL,
    "contactPoint": [
      {
        "@type": "ContactPoint",
        "email": SUPPORT_EMAIL,
        "contactType": "customer support"
      },
      {
        "@type": "ContactPoint",
        "email": CONTACT_EMAIL,
        "contactType": "general inquiries"
      }
    ],
    "description": "TextToSpeechH AI is a leading AI text-to-speech platform transforming scripts into realistic human voiceovers for free.",
    "sameAs": [
      OFFICIAL_INSTAGRAM
    ]
  };
}

function getWebSiteSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "name": BRAND_NAME,
    "alternateName": "TextToSpeechH",
    "url": DOMAIN
  };
}

function getSoftwareApplicationSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    "name": BRAND_NAME,
    "url": DOMAIN,
    "operatingSystem": "All",
    "applicationCategory": "MultimediaApplication",
    "offers": {
      "@type": "Offer",
      "price": "0.00",
      "priceCurrency": "USD"
    },
    "description": "Convert text into realistic AI voices instantly using TextToSpeechH AI. Free online text-to-speech with natural voices, MP3 downloads, and support for multiple languages."
  };
}

function getFAQSchema(faqs) {
  const defaultFaqs = [
    {
      q: "Is TextToSpeechH AI completely free?",
      a: "Yes, TextToSpeechH AI is 100% free to use for generating realistic text-to-speech voiceovers with no required credit card."
    },
    {
      q: "How many words can I convert with TextToSpeechH AI?",
      a: "TextToSpeechH AI supports long scripts from 2,500 up to 10,000+ words with intelligent paragraph chunking."
    },
    {
      q: "Can I download MP3 voiceovers for free?",
      a: "Yes, you can instantly download high bitrate MP3 voiceover files generated by TextToSpeechH AI."
    }
  ];

  const list = faqs || defaultFaqs;
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": list.map(item => ({
      "@type": "Question",
      "name": item.q,
      "acceptedAnswer": {
        "@type": "Answer",
        "text": item.a
      }
    }))
  };
}

function getBreadcrumbSchema(items) {
  const defaultItems = [
    { name: "Home", url: DOMAIN },
    { name: "Free AI Voice Generator", url: `${DOMAIN}/` }
  ];
  const list = items || defaultItems;

  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": list.map((item, index) => ({
      "@type": "ListItem",
      "position": index + 1,
      "name": item.name,
      "item": item.url
    }))
  };
}

function getArticleSchema(title, description, url, datePublished, dateModified) {
  return {
    "@context": "https://schema.org",
    "@type": "Article",
    "headline": title,
    "description": description,
    "url": url,
    "datePublished": datePublished || "2026-07-29",
    "dateModified": dateModified || "2026-07-29",
    "author": {
      "@type": "Organization",
      "name": "TextToSpeechH AI Editorial Team",
      "url": DOMAIN
    },
    "publisher": {
      "@type": "Organization",
      "name": BRAND_NAME,
      "url": DOMAIN,
      "logo": {
        "@type": "ImageObject",
        "url": `${DOMAIN}/logo.svg`
      }
    },
    "mainEntityOfPage": {
      "@type": "WebPage",
      "@id": url
    },
    "image": `${DOMAIN}/og-image.png`
  };
}

module.exports = {
  DOMAIN,
  BRAND_NAME,
  CONTACT_EMAIL,
  SUPPORT_EMAIL,
  OFFICIAL_INSTAGRAM,
  getOrganizationSchema,
  getWebSiteSchema,
  getSoftwareApplicationSchema,
  getFAQSchema,
  getBreadcrumbSchema,
  getArticleSchema
};
